Fix the Ballerina.toml updating before the Ballerina push
ballerina-platform/module-ballerinax-postgresql pull request #6
Opened 2021-04-18 21:29 UTC by SasinduDilshara

## Purpose
>Part of ballerina-platform/ballerina-standard-library#1247
## Examples

## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests

2021-04-19 03:58 UTC, BuddhiWathsala commented
@SasinduDilshara, it's better if you can add the Github action as here(https://github.com/ballerina-platform/module-ballerina-time/pull/100/files). That action will help to publish artifacts to the Ballerina central manually if something goes wrong in the release process.

2021-04-19 04:55 UTC, SasinduDilshara commented
> @SasinduDilshara, it's better if you can add the Github action as here(https://github.com/ballerina-platform/module-ballerina-time/pull/100/files). That action will help to publish artifacts to the Ballerina central manually if something goes wrong in the release process.

I will add

2021-04-21 07:12 UTC, BuddhiWathsala requested changes

2021-04-21 07:12 UTC, BuddhiWathsala commented on .github/workflows/central-publish.yml
> +                    ./gradlew clean build -PpublishToCentral=true
```suggestion
                    ./gradlew clean build -PpublishToCentral=true
                    
```

2021-04-21 07:22 UTC, BuddhiWathsala approved these changes
LGTM

2021-04-27 19:47 UTC, merged